### PR TITLE
✨ make customizable the `NEVER` text

### PR DESCRIPTION
**Pull request by demir09**
## Changes
Made giveaway paused remaining text customizable because language difference.

## Status

- [x] These changes have been tested and formatted properly.
- [ ] This PR includes only documentation changes (JSDoc, README or typings), no code change.
- [x] This PR introduces some breaking changes.

### CODE REVIEW

**Review by Androz2091 — CHANGES_REQUESTED** [review]
Thank you for your contribution. You should also :
- update the typings to add the new property to pause options
- update the constants to add the new property to the jsdoc comments and the default pause options

**Comment by Nico105** [comment]
> Thank you for your contribution. You should also :
> 
> * update the typings to add the new property to pause options
> * update the constants to add the new property to the jsdoc comments and the default pause options

what about _maybe_ adding a getter to support ``Drawing: {this.timestamp ?? 'Never''}` + notice in readme
or would that be too user-unfriendly?

**Comment by demir09** [comment]
Sorry, I am deleted the fork repository. I am reopening.

**Comment by demir09** [comment]
@Androz2091 please delete this

**Pull request closed without merging**
