### PR TITLE
Support for custom reaction

### PR DESCRIPTION
**Pull request by misa-coder**
Now it supports custom reaction for the giveaways too.

### CODE REVIEW

**Comment by NicoHd105** [comment]
So can a custom emoji be used for the reaction with that change?

**Comment by misa-coder** [comment]
Yahh @NicoHd105 I tested in my bot and it works with both custom and discord emojis

**Comment by misa-coder** [comment]
The main issue is actually in 75 line where androz use packet.d.emoji.name where giveaway.reaction is an id that's why it always return in custom emoji case.

**Comment by NicoHd105** [comment]
Does the "giveawayreactionAdded" event works for you when you use a custom emoji?

**Comment by misa-coder** [comment]
Yahh @NicoHd105 that's why I pull this request

**Comment by NicoHd105** [comment]
👍Thanks

**Pull request merged**
