### PR TITLE
Update GiveawaysManager.html

### PR DESCRIPTION
**Pull request by Dragonizedpizza**

### CODE REVIEW

**Comment by Nico105** [comment]
Idk if this pr would change the website automatically when merged without clicking some button/if because of versioning it would even be good to merge it only for this one change

Explanation:
JSDoc can automatically use the comments in the code to generate a website
So the missing bracket your trying to fix has already been fixed in the referring comment in the dev branch (scroll down in manager.js)
Means when the dev branch gets merged and the new version is released androz just has to run a command and he gets the updated files

**Comment by Androz2091** [comment]
The documentation is automatically generated (I don't even have to run a command myself) when something is pushed on the master branch.

**Comment by Dragonizedpizza** [comment]
could you merge it then

**Comment by Dragonizedpizza** [comment]
alr

**Pull request closed without merging**
