### PR TITLE
✨ requiredParticipationCount, requiredWinnercount, noValidEndingInterval

### PR DESCRIPTION
**Pull request by Nico105**
Thoughts?
As far as I tested it, it works.
Better variable names are of course accepted.
Better implementation of course accepted.

### End Command
Currently `requiredParticipationCount` will only be trigger by auto-ending, an `end` command with the `end()` function ignores it.
But `requiredWinnercount` will always be triggered (= even with an `end` command)

_2nd sentence because otherwise we would have to move `requiredWinnercount` handling into the `roll()` function and then a `reroll` command would also be affected by `requiredWinnercount` and I don't think that that is really wanted. The only thing that we could do if we should do it like that (lmk your opinion) is adding an argument to the `end` and `reroll` function where people can set `useRequiredWinnercount` to true if they like but otherwise nothing will be affected._

### CODE REVIEW

**Review by Androz2091 — CHANGES_REQUESTED** [review]
So, first of all thank you so much for your work :grin:
I *think* that we should remove `noValidEndingInterval`. Yes. I'm sorry. :grimacing:
I will do the changes, don't worry.

**Comment by Nico105** [comment]
As a thought, we could scrap `requiredParticipationCount` and just use the ` requirements` option [that you already added to the giveaway data](https://github.com/Androz2091/discord-giveaways/blob/490e5c222e9518add406949244f0b1e938091246/src/Giveaway.js#L289)
= `endRequirements: (giveaway) => giveaway.message.reactions.cache.get(giveaway.reaction).users.cache.size - 1 >= 100`
#107

**Comment by imranbarbhuiya** [comment]
Why it's still WIP?

**Comment by Nico105** [comment]
> Why it's still WIP?

Waiting on Androz to tell the direction where this should go.

**Comment by Nico105** [comment]
The future approach should be like mentioned in: https://github.com/Androz2091/discord-giveaways/pull/213#issuecomment-784138541
_I already started working on it a little, but it will take its time_

**Pull request closed without merging**
