### PR TITLE
🐛 fix: typings for deleteGiveaway and delete

### PR DESCRIPTION
**Pull request by Dev-CasperTheGhost**
* Minor: Return `boolean` instead of `void` 

This change was made because in the examples it says "Don't forget to return something" and to make TS happy 😅

### CODE REVIEW

**Comment by Nico105** [comment]
Hmm, I wonder if that should be done for the normal delete function as well, since it's also "public".
I assume it was made as "best pratice" in the DB examples to say "everything went well".

**Comment by Dev-CasperTheGhost** [comment]
Possibly, let me know if I should change it too 😄

**Comment by Nico105** [comment]
If you would be so kind

**Comment by Dev-CasperTheGhost** [comment]
> If you would be so kind

Will do tomorrow since I’m about to get off for today

**Comment by Dev-CasperTheGhost** [comment]
@Nico105 done 😄!

**Review by Nico105 — APPROVED** [review]

**Comment by Nico105** [comment]
👍 Thank you

**Pull request merged**
