### PR TITLE
✏️Use array fill instead of looping over the entries

### PR DESCRIPTION
**Pull request by Lebyy**
## Changes
This pr uses the js Array and Array fill method to multiple the user x many times instead of looping over the array.
The purpose of this pr is to solve the heap errors if the number is VERY LARGE thrown by node.

## Status

- [x] These changes have been tested and formatted properly.
- [ ] This PR includes only documentation changes (JSDoc, README or typings), no code change.
- [ ] This PR introduces some breaking changes.

### CODE REVIEW

**Comment by Dragonizedpizza** [comment]
you don't need to change the variable's value and concat the array, you could just do `userArray.push(...Array(highestBonusEntries).fill(user))`

**Comment by Lebyy** [comment]
> userArray.push(...Array(highestBonusEntries).fill(user))

Oh yes, added that

**Comment by Nico105** [comment]
image
about how large numbers are we talking about?
And can you explain a little more/proof the better efficiency, cause _ik its not to pratical but_ a little benchmarking and googling didn't really bring results...

**Comment by Lebyy** [comment]
> image about how large numbers are we talking about? And can you explain a little more/proof the better efficiency, cause _ik its not to pratical but_ a little benchmarking and googling didn't really bring results...

Like 20k.

**Comment by Nico105** [comment]
Now, I tested it with a bot and 2 entrants, 1 million bE `bonus: (member) => true ? 1_000_000 : null` and it was actually fill who got `Maximum call stack size exceeded` whereas the loop got it through...

**Comment by Dragonizedpizza** [comment]
after some googling, I found this https://stackoverflow.com/a/53029824

The current way of doing it is the fastest.

**Comment by Lebyy** [comment]
> after some googling, I found this https://stackoverflow.com/a/53029824
> 
> The current way of doing it is the fastest.

So we should use `let a = new Array(n); for (let i=0; i<n; ++i) a[i] = 0;` I think.

**Comment by Nico105** [comment]
> let a = new Array(n)

image
normal push is still faster.
and going to 1mill, the 2nd one gets `Maximum call stack size exceeded`.

**Comment by Dragonizedpizza** [comment]
@Nico105 what are you using for the benchmarking?

**Comment by Nico105** [comment]
> @Nico105 what are you using for the benchmarking?

https://jsbench.me

**Comment by Nico105** [comment]
> > let a = new Array(n)
> 
> image normal push is still faster. and going to 1mill, the 2nd one gets `Maximum call stack size exceeded`.

Any comments? If not then I would close this, unless...

**Pull request closed without merging**
